### ISSUE TITLE
Xóa khách sạn - Owner

### ISSUE THREAD

**Issue by thy015** [thy015/takeabreath#100]
--Không hiện thông báo, không tự refresh

**Comment by thy015** [comment]
-- Không có nút gỡ thẻ

**Comment by thy015** [comment]
-- Không được xóa khách sạn và phòng mà khách đang đặt

**Comment by thy015** [comment]
-- chưa count số lượng đặt phòng

**Comment by thy015** [comment]
thy: chỉnh DB loại phòng

**Comment by TanPhuc2804** [comment]
done đếm số lượng đặt phòng

**Comment by TanPhuc2804** [comment]
xong ko xóa đươc phòng khách sạn

**Comment by thy015** [comment]
Thy: thêm type cố định cho loại khách sạn - DB Owner

**Comment by TanPhuc2804** [comment]
xong xóa hiện thông báo khi xóa hotel tự động cập nhạt ko cần refresh

**Comment by quocanhhoclaptrinh** [comment]
không tạo được voucher Owner

**Comment by thy015** [comment]
đã thêm DB loại phòng, lấy qua http://localhost:4000/api/hotelList/roomTypes

**Comment by thy015** [comment]
đã thêm DB loại ksan, lấy qua: http://localhost:4000/api/hotelList/hotelTypes
