### ISSUE TITLE
Bug in Admin

### ISSUE THREAD

**Issue by thy015** [thy015/takeabreath#101]
-- Chart Data chưa cập nhập

**Comment by thy015** [comment]
Lọc khách sạn Admin

**Comment by thy015** [comment]
thy làm DB voucher admin

**Comment by thy015** [comment]
fix display phòng trong khách sạn

**Comment by thy015** [comment]
in tất cả hóa đơn thay vì in từng cái

**Comment by thy015** [comment]
đã add DB vouchersys

**Comment by quocanhhoclaptrinh** [comment]
Có 2 thanh tìm kiếm trong Khách Sạn
