### ISSUE TITLE
Lỗi tìm kiếm Địa Điểm không hiển thị

### ISSUE THREAD

**Issue by quocanhhoclaptrinh** [thy015/takeabreath#161]
![image](https://github.com/user-attachments/assets/d3c1f2e0-85e7-4fb1-a296-dd3b024c8da5)
**Summary**:Lỗi tìm kiếm Thành Phố Hồ Chí Minh
Step:
1.Nhập vào tìm kiếm địa điểm Thành Phố Hồ Chí Minh
2.Nhấn Tìm Kiếm

**Comment by quocanhhoclaptrinh** [comment]
![image](https://github.com/user-attachments/assets/99f29d62-d60c-48fb-80af-6ff70ea26967)
Summary:Lỗi tìm kiếm Bắc Giang
Step:
1.Nhập vào tìm kiếm địa điểm Bắc Giang
2.Nhấn Tìm Kiếm

**Comment by quocanhhoclaptrinh** [comment]
![image](https://github.com/user-attachments/assets/6f0c2b49-da8f-478f-bda9-ce8487f854aa)
**Summary**:Lỗi tìm kiếm Phan Thiết
**Step**:
1.Nhập vào tìm kiếm địa điểm Phan Thiết
2.Nhấn Tìm Kiếm

**Comment by thy015** [comment]
fixed
